### ISSUE TITLE
安装报错。

### ISSUE THREAD

**Issue by xtheo** [protream/tickets#1]
安装报错:

>root@VM-102-99-debian:~# pip install tickets
Downloading/unpacking tickets
  Could not find any downloads that satisfy the requirement tickets
No distributions at all found for tickets
Storing complete log in /root/.pip/pip.log

查看log文件:
>root@VM-102-99-debian:~# cat /root/.pip/pip.log
------------------------------------------------------------
/usr/bin/pip run on Sat Jun 11 21:57:15 2016
Downloading/unpacking tickets

>  Getting page http://pypi.python.org/simple/tickets
  URLs to search for versions for tickets:
  * http://pypi.python.org/simple/tickets/
  Getting page http://pypi.python.org/simple/tickets/
  Analyzing links from page https://pypi.python.org/simple/tickets/
    Skipping link https://pypi.python.org/packages/79/bf/27ec9203a03d95e53d9ea530a1a3130c7e661a419c08fd98c16eca4e8797/tickets-0.1-py2-none-any.whl#md5=c75da25678bcbed13795eccff7eebd66 (from https://pypi.python.org/simple/tickets/); unknown archive format: .whl
  Could not find any downloads that satisfy the requirement tickets

>No distributions at all found for tickets

>Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 104, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 245, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 978, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 157, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
>DistributionNotFound: No distributions at all found for tickets

我的系统是debian 7 32位:
>
root@VM-102-99-debian:~# cat /etc/debian_version
7.10

python 版本是2.7
>
root@VM-102-99-debian:~# python --version
Python 2.7.3

**Comment by xtheo** [comment]
好吧，手动安装了requests,docopt和 prettytable 后正常安装了。
pip install requests docopt prettytable

**Comment by protream** [comment]
@xtheo 运行正常吗?

**Comment by xtheo** [comment]
运行一切正常。谢谢你！
