### ISSUE TITLE
Error in Python 2.7.11 

### ISSUE THREAD

**Issue by blue7wings** [protream/tickets#4]
`/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
Traceback (most recent call last):
  File "/usr/local/bin/tickets", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/dist-packages/tickets/core.py", line 231, in cli
    rows = resp.json()['data']['datas']
TypeError: 'int' object has no attribute '__getitem__'
`

**Comment by protream** [comment]
能给出你的查询数据吗？

**Comment by blue7wings** [comment]
tickets 上海 北京 2016620

**Comment by protream** [comment]
@blue7wings 在我的机器（ubuntu 14.04）是没有问题。 这应该是网络问题，服务器返回-1，没有返回数据, 程序也有一点小问题， 没有捕捉到这个错误。另外，你有没有再试试，换换参数也不行吗？

**Comment by JoeMinty** [comment]
我也有同样的问题， mac下，请问作者是否已经解决这个问题？
